version: 2

buildSteps: &buildSteps
  - setup_remote_docker
  - checkout
  - run:
      name: install-npm
      command: npm install
  - run:
      name: test
      command: npm test

jobs:
  'node-12':
    docker:
      - image: cimg/node:12.22
    working_directory: ~/node-12
    steps: *buildSteps

  'node-14':
    docker:
      - image: cimg/node:14.19
    working_directory: ~/node-14
    steps: *buildSteps

  'node-16':
    docker:
      - image: cimg/node:16.14
    working_directory: ~/node-16
    steps: *buildSteps

workflows:
  version: 2
  build:
    jobs:
      - 'node-12'
      - 'node-14'
      - 'node-16'
